language: r
sudo: false
cache: packages

install:
- R -e "install.packages('data.table')"
- R -e "install.packages('dplyr')"
- R -e "install.packages('ggplot2')"
- R -e "install.packages('splitstackshape')"

script:
- R -e "source('global.R')"
- R -e "source('myplot.R')"
- R -e "myplot(df)"
- R -e "quit(status=1)"
