language: r
sudo: false
cache: packages

install:
- Rscript -e "install.packages('data.table')"
- Rscript -e "install.packages('dplyr')"
- Rscript -e "install.packages('ggplot2')"
- Rscript -e "install.packages('splitstackshape')"

script:
- Rscript -e "source('build.R')"

deploy:
     provider: releases
     api_key:
         secure: <your key>
     file:
         - myplot.png
     skip_cleanup: true
     on:
         repo: fmichelsendis/sendis_ci
         tags: true
